# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'user_ui' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.2'
  pod 'AlamofireImage', '~> 4.1'
  pod 'RealmSwift'
  # Pods for user_ui

  target 'user_uiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'user_uiUITests' do
    # Pods for testing
  end

end
